const fs=require('fs');
const vm=require('vm');
const assert=require('assert/strict');
const source=fs.readFileSync(require('path').join(__dirname,'..','dist','app.js'),'utf8');
const nodes=new Map(),events={},registered=[];
function node(selector){
 if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',value:'',dataset:{},checked:false,open:false,disabled:false,handlers:{},classList:{toggle(){},add(){},remove(){}},setAttribute(){},setCustomValidity(value){this.validation=value;},addEventListener(name,fn){this.handlers[name]=fn;},showModal(){this.open=true;},close(){this.open=false;}});
 return nodes.get(selector);
}
class DemoFormData{constructor(form){this.fields=form._fields||{};}get(key){return this.fields[key]??null;}}
const context=vm.createContext({console,Intl,setTimeout:()=>0,clearTimeout(){},AbortController,FormData:DemoFormData,navigator:{clipboard:{writeText:async()=>{}}},document:{querySelector:node,addEventListener:(name,fn)=>events[name]=fn,modelContext:{registerTool:(tool)=>registered.push(tool)}},window:{scrollTo(){},addEventListener(){}}});
vm.runInContext(source,context);
const run=code=>vm.runInContext(code,context);
assert.equal(run('state.records.length'),4);
assert.match(node('#main-content').innerHTML,/我的荣誉档案/);
assert.equal(run('state.shared'),false);
run("state.queryAttempted=true;state.queryCode=dossierCode;setRole('enterprise')");
assert.match(node('#main-content').innerHTML,/该档案未授权公开/);
assert.doesNotMatch(node('#main-content').innerHTML,/校级优秀学生奖学金/);
run('toggleShare()');
assert.match(node('#main-content').innerHTML,/校级优秀学生奖学金/);
assert.doesNotMatch(node('#main-content').innerHTML,/数据驱动的校园服务优化研究/);
run('toggleShare()');
assert.match(node('#main-content').innerHTML,/该档案未授权公开/);
assert.doesNotMatch(node('#main-content').innerHTML,/校级优秀学生奖学金/);
run("go('loan')");
node('#loan-record').value='r2';node('#loan-amount').value='1801';node('#loan-days').value='30';
assert.equal(run('loanValidation()'),false);
assert.match(node('#loan-error').textContent,/不得超过/);
node('#loan-amount').value='1000';node('#loan-consent').checked=true;node('#loan-purpose').value='必要学习与生活支出';
events.submit({preventDefault(){},target:{id:'loan-form'}});
assert.equal(run('state.loan.amount'),1000);
assert.match(node('#main-content').innerHTML,/待银行独立审查/);
assert.match(node('#main-content').innerHTML,/不会放款/);
run("submitCertification('r3')");
assert.equal(run("state.records.find(r=>r.id==='r3').status"),'pending');
assert.throws(()=>run("submitCertification('r3')"));
run("go('archive')");
events.submit({preventDefault(){},target:{id:'record-form',dataset:{editId:'r1'},_fields:{title:'更新后的奖学金',description:'一等奖',institution:'示例学校',date:'2026-10-08',kind:'scholarship',proof:{name:''}}}});
assert.equal(run("state.records.find(r=>r.id==='r1').status"),'unverified');
assert.equal(run("state.records.find(r=>r.id==='r1').version"),2);
assert.equal(run("state.shareIds.includes('r1')"),false);
assert.equal(run("eligibleRecords().some(r=>r.id==='r1')"),false);
events.submit({preventDefault(){},target:{id:'record-form',dataset:{editId:''},_fields:{title:'<script>bad()</script>',description:'记录示例',institution:'示例学校',date:'2026-10-08',kind:'paper',proof:{name:'test.pdf'}}}});
assert.equal(run('state.records.length'),5);
assert.match(node('#main-content').innerHTML,/&lt;script&gt;bad/);
assert.doesNotMatch(node('#main-content').innerHTML,/<script>bad/);
run('state.user.verified=false');
assert.equal(run('eligibleRecords().length'),0);
run('recordForm()');
assert.equal(run('state.page'),'student');
node('#student-consent').checked=true;
events.submit({preventDefault(){},target:{id:'student-form'}});
assert.equal(run('state.user.verified'),true);
for(const page of ['archive','student','loan','share']){run(`go('${page}')`);assert.doesNotMatch(node('#main-content').innerHTML,/undefined/);}
assert.equal(registered.length,3);
assert.throws(()=>registered.find(t=>t.name==='navigate_qingyu_demo').execute({page:'bad'}));
registered.find(t=>t.name==='navigate_qingyu_demo').execute({page:'share'});
assert.equal(run('state.page'),'share');
run('state.shared=true');
assert.equal(registered.find(t=>t.name==='disable_qingyu_demo_disclosure').execute().disclosureEnabled,false);
console.log(JSON.stringify({result:'passed',checks:['default privacy','authorized query scope','immediate authorization withdrawal','loan amount cap','loan independent review state','certification submission','edit invalidates certification and disclosure','create and escape honor record','student verification gating','all core views','WebMCP contract with stub context'],browserLayout:'not run: static preview unavailable'}));
